version: 2.1

jobs:
  build:
    parameters:
      node_image:
        type: string
    docker:
      - image: << parameters.node_image >>
    working_directory: ~/project
    steps:
      - checkout
      - restore_cache:
          keys:
            - npm-deps-v2-<< parameters.node_image >>-{{ checksum "package-lock.json" }}
            - npm-deps-v2-<< parameters.node_image >>-
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: npm-deps-v2-<< parameters.node_image >>-{{ checksum "package-lock.json" }}
          paths:
            - ~/.npm
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run smoke test
          command: NEMS_RUN_SMOKE=true npm run functional:smoke

workflows:
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              node_image:
                - cimg/node:18.20
                - cimg/node:24.0
